### ISSUE TITLE
Cannot add picture to a shave

### ISSUE THREAD

**Issue by tjunge** [RobTS/ShavingBuddy-Support#14]
When preparing to share a save, I tap on "Add  Image", and select an image.

Expected behaviour:

The image gets selected, displayed and I can continue to the next step

Actual behaviour:

I get a "Something went wrong" dialogue over the entire app. The only possible action is to tap "OK"

**Comment by RobTS** [comment]
Hi @tjunge, there was an issue when the database was migrated recently. I was under the assumption all user interactions were happening with server A (where your Cloud backups are kept), but there is in fact a server B that just handles image uploads and I was not aware of at the time (as rarely as the updates happen, they usually involve huge changes). 

It has been updated now and everything should be in working order. Images between 8.-11.11.2020 might have to be reuploaded. An update will eventually follow that will remove the old server altogether. Enjoy the app!
